-- MySQL Script generated by MySQL Workbench
-- Fri 08 May 2026 10:55:43 AM -05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`document_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`document_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`people`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`people` (
  `id` INT NOT NULL,
  `document_type_id` INT NOT NULL,
  PRIMARY KEY (`id`, `document_type_id`),
  INDEX `fk_people_document_type_idx` (`document_type_id` ASC) VISIBLE,
  CONSTRAINT `fk_people_document_type`
    FOREIGN KEY (`document_type_id`)
    REFERENCES `mydb`.`document_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`enterprises`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`enterprises` (
  `id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`document_class`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`document_class` (
  `id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`document`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`document` (
  `id` INT NOT NULL,
  `people_id` INT NOT NULL,
  `document_class_id` INT NOT NULL,
  `enterprises_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_document_people1_idx` (`people_id` ASC) VISIBLE,
  INDEX `fk_document_document_class1_idx` (`document_class_id` ASC) VISIBLE,
  INDEX `fk_document_enterprises1_idx` (`enterprises_id` ASC) VISIBLE,
  CONSTRAINT `fk_document_people1`
    FOREIGN KEY (`people_id`)
    REFERENCES `mydb`.`people` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_document_document_class1`
    FOREIGN KEY (`document_class_id`)
    REFERENCES `mydb`.`document_class` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_document_enterprises1`
    FOREIGN KEY (`enterprises_id`)
    REFERENCES `mydb`.`enterprises` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Services`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Services` (
  `Id` INT NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`details` (
  `id` INT NOT NULL,
  `document_id` INT NOT NULL,
  `Services_Id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_details_document1_idx` (`document_id` ASC) VISIBLE,
  INDEX `fk_details_Services1_idx` (`Services_Id` ASC) VISIBLE,
  CONSTRAINT `fk_details_document1`
    FOREIGN KEY (`document_id`)
    REFERENCES `mydb`.`document` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_details_Services1`
    FOREIGN KEY (`Services_Id`)
    REFERENCES `mydb`.`Services` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
